### ISSUE TITLE
Workspaces don't work 

### ISSUE THREAD

**Issue by rafal11ck** [DemonKingSwarn/dotfiles#1]
Active workspace indicator doesn't work correctly.

https://github.com/DemonKingSwarn/dotfiles/assets/76795799/ea6db65d-7971-43d5-8d55-d60338f9d0af

    1. open workspace

    2. open window

    3. go to other screen

    4. open window

    5. go to another monitor swap to empty workspace

    6. go back to monitor

    7. go to window from 2

**Comment by rafal11ck** [comment]
Not active

**Comment by DemonKingSwarn** [comment]
it works bro
